post_path: opa-cfn-tag-policy.md
replaces:
  - from: https://github-link-card.s3.ap-northeast-1.amazonaws.com/x-color/opa-cfn-tag-policy.png
    to: https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/279498/e1d193e6-f461-8290-cf57-5af7e40254bd.png
id: 43f1d38ae3380f443d86
hash: bf8da347a523334c543ac14d3a8eb25cf40d1dfc3c8867dcf89c61148f9a22ff
